Phonon redeem
GridPlus/phonon-client pull request #101
Opened 2022-03-11 23:34 UTC by maevyn11

We'll have to merge one or the other of the active PRs before these can both go in. 

Working ETH redeem and abstractions to build more chain handling on top included.

2022-03-14 19:44 UTC, npmaile requested changes

2022-03-14 19:44 UTC, npmaile commented on chain/ethChainService.go
> +	// "net/http"
remove commented imports

2022-03-14 19:44 UTC, npmaile commented on chain/ethChainService.go
> +//London Signing Code
I assume this will be used in a future iteration, but isn't necessary right now. Maybe should go on a branch instead of sitting commented out.

2022-03-14 19:44 UTC, npmaile commented on chain/ethChainService.go
> +func NewEthChainService() (*EthChainService, error) {
mild nitpick, but should return the interface type instead of a pointer to struct type unless there is eth specific exported functions to be used.

2022-03-14 19:44 UTC, npmaile commented on chain/multiChainRouter.go
> +func InitChainService(cur model.CurrencyType) (ChainService, error) {
possibly store these in a static map someplace instead of a long switch case.

2022-03-14 19:44 UTC, npmaile commented on config/config.go
> +	"github.com/spf13/viper"
viper will likely work for now, but as we get more into trying to make this friendly for less technical users, we may wish to have configurations set in the app that are persisted across runs. I'm not exactly sure of libraries to support this, and we may be able to leverage viper anyway despite not being exaaaaactly the normal viper use case.

2022-03-14 19:44 UTC, npmaile commented on gui/api.go
> +		return nil, fmt.Errorf("unable to find sesion")
s/sesion/session

2022-03-14 19:44 UTC, npmaile commented on gui/api.go
> +		return nil, fmt.Errorf("unable to find sesion")
s/sesion/session/

2022-03-14 19:44 UTC, npmaile commented on model/phonon.go
> +	//idk if this is good
Be more  confident in yourself!

2022-03-14 19:44 UTC, npmaile commented on phonon.yml
> +#Sample Config File (Fill in values and store in $HOME/.phonon/phonon.yml)
should search $XDG_CONFIG_HOME/.phonon/phonon.yml followed by $HOME/.phonon/phonon.yml followed by /usr/var/phonon/phonon.yml at least on linux systems
we need to figure out what to do on windows systems as well.

2022-03-14 19:44 UTC, npmaile commented on chain/ethChainService.go
> +	if suggestedGasPrice.Cmp(onChainBalance) != -1 {
This check should be done before destruction of the phonon on-card using the public key to prevent people from destroying phonons they won't be able to redeem and ending up with a private key they have to store someplace.

2022-03-16 16:44 UTC, maevyn11 commented on chain/ethChainService.go
> +	// "net/http"
done

2022-03-16 16:44 UTC, maevyn11 commented on chain/ethChainService.go
> +//London Signing Code
yea, possibly used in future, but not useful enough code to be worth keeping around. Removed it.

2022-03-16 16:55 UTC, maevyn11 commented on chain/multiChainRouter.go
> +func InitChainService(cur model.CurrencyType) (ChainService, error) {
Yea, realized that map exists as mcr.chainServices and it's being built already with InitBuiltinChainServices. 

Think I was getting ahead of myself with the lazy loading functions imagining that 3rd party implementations would be pluggable. Since that's not being implemented here, just going to remove that code in favor of the simple initialization of all supported chainServices on startup.

2022-03-16 17:00 UTC, maevyn11 commented on chain/ethChainService.go
> +	if suggestedGasPrice.Cmp(onChainBalance) != -1 {
Yea, I agree. I thought of that as I was working through this as well. :( 
  
Unfortunately, that's pretty hard to do within this paradigm, because we can't call back to session from within this method to get that data mid flow. I guess we would have to break up RedeemPhonon into multiple steps that get orchestrated by Session, like ValidateRedeemReady and then RedeemPhonon. This should probably also account for sending info back to the frontend so the user can view things like gas price and accept them before executing the redeem. 

Since this would entail significant additional coding which we don't necessarily need for testnet, I suggest we create an issue for a v2 of this interface definition that improves upon the full user flow and defer this work till then.

2022-03-16 17:03 UTC, maevyn11 commented on config/config.go
> +	"github.com/spf13/viper"
yea agreed we'll want to support that. I believe viper does actually have good support for not just reading but also writing config files, so things are saved across runs.

2022-03-16 17:05 UTC, maevyn11 commented on gui/api.go
> +		return nil, fmt.Errorf("unable to find sesion")
done

2022-03-16 17:05 UTC, maevyn11 commented on gui/api.go
> +		return nil, fmt.Errorf("unable to find sesion")
done

2022-03-16 17:15 UTC, maevyn11 commented on phonon.yml
> +#Sample Config File (Fill in values and store in $HOME/.phonon/phonon.yml)
https://github.com/GridPlus/phonon-client/issues/103

2022-03-16 17:20 UTC, maevyn11 commented on chain/ethChainService.go
> +	if suggestedGasPrice.Cmp(onChainBalance) != -1 {
https://github.com/GridPlus/phonon-client/issues/104

2022-03-24 16:58 UTC, merged