ERC721 and ERC20 Currency Types
GridPlus/phonon-client pull request #112
Opened 2022-03-28 04:11 UTC by soysenor

REPL
- Added `VerifyBalance` method.  Takes `keyIndex` for Phonon, then routes through multiChainRouter to ETHChainService, and switches between `checkERC721Balance`, `checkETHBalance`, `checkERC20Balance` pending Currency Type with support from helper function `checkFetchFromAddress`.  Go-bindings for ERC721 and ERC20 contract are currently sourced from one of my repos, but should be moved into phonon. 
- Incorporated Tagging into `SetDescriptor`.  Gets required tags for ERC721 and ERC20 (see `CurrencyTypeTagsRequired` map on model/phonon.go), prompts user for inputs (`TagPhononContractAddress` and `TagPhononContractTokenID` - see card/apdu too), and passes user inputs `[]PhononTag` to `AddTags` method on Phonon model to be structured according to TLV standard.
- Added `ChainID` as a mandatory 4th parameter for `SetDescriptor`.

GUI
- Updated `initDepositPhonons` to take `Tags` as slices of key value strings (see `[][]PhononTag`), which are parsed into TLV standard via `AddTags` method in `initDepositPhonons` in session/session.   But because `setDescriptor` isn't processed until `FinalizeDepositPhonons`, I had to work through `UnmarshalJSON` and `MarshalJSON` on model/phonon for ExtendedTLV to pass data back and forth between web and client.  I'm sure you'll have a more sophisticated approach to this, but I made it work for my tags (see `marshalTags`).  

Additional Notes:
- Currently the following work for ERC721 and ERC20:  `create`, `setDescriptor`, `initDepositPhonons`, `verifyBalance`.
- Not fully integrated: `redeem`.   You'll see I updated the `RedeemPhonon` method for EthChainService  to switch on currencyType; `redeemETH` and `redeemToken`.  This hasn't been fully tested yet.  Is a little tricky with the bug in the applet limiting currency types, and with the react app actively being worked on.  But it's close so I'm incorporating the code in anyway.  Also, I would not call redemption for ERC20 nor ERC721 fully integrated until the pre-requisite transfer of ETH to the phonon is thought out; this needs to be done in the UI.
- Added CurrencyType `EthereumERC721` and `EthereumERC20` to model/phonon.

2022-03-31 22:04 UTC, npmaile requested changes

2022-03-31 22:04 UTC, npmaile commented on repl/phonons.go
> +	requiredTags := model.CurrencyTypeTagsRequired[currencyType]
@maevyn11 I'm not sure what needs to be done with the tags

2022-03-31 22:04 UTC, npmaile commented on repl/phonons.go
> +			c.Printf("Input %v: ", tag)
%+v gives the field names as well, which may be useful

2022-04-04 20:00 UTC, maevyn11 requested changes
Some initial feedback.

2022-04-04 20:00 UTC, maevyn11 commented on chain/ethChainService.go
> +	if leftOverValue < 0 {
This doesn't compile on my machine. I think with the *big.Int you'll need to use leftOverValue.Cmp() and check the output, unless there is some big.Int operator support in a newer version of golang I'm not aware of.

2022-04-04 20:00 UTC, maevyn11 commented on chain/ethChainService.go
> +func (eth *EthChainService) checkFetchFromAddress(p *model.Phonon) error {
I don't think this function is necessary, simply calling eth.DeriveAddress() will ensure that there is an address present. eth.DeriveAddress actually never returns an error, so the error check here isn't needed.

2022-06-26 02:51 UTC, closed without merging

2022-06-26 02:52 UTC, soysenor commented
Postponing work until after testnet.