Init route
GridPlus/phonon-client pull request #156
Opened 2022-07-07 21:30 UTC by maevyn11

2022-07-08 18:26 UTC, npmaile requested changes

2022-07-08 18:26 UTC, npmaile commented on gui/swagger.yaml
> -        "404":
not sure why no cards being plugged in is a 500 error

2022-07-11 19:09 UTC, maevyn11 commented on gui/swagger.yaml
> -        "404":
idk, seemed like a 404 page not found was misleading since the page is there, it's just it can't serve the expected response because there's no card plugged in behind the scenes. My thought is it's a 500 because the server can't handle the request given it's state. Neither one really seems right but I wasn't sure what else to use.

2022-07-11 19:50 UTC, maevyn11 commented on gui/swagger.yaml
> -        "404":
OK, guess that's my misconception then, 404 is just as good so no reason to change it. Fixed https://github.com/GridPlus/phonon-client/pull/156/commits/9252c0b78a417633cc7506e4a6d124ad9893fcb7

2022-07-11 20:47 UTC, npmaile requested changes

2022-07-11 21:02 UTC, npmaile approved these changes

2022-07-11 21:10 UTC, douglance approved these changes

2022-07-11 21:14 UTC, merged