initial implementation of BER-TLV parser
GridPlus/phonon-client pull request #166
Opened 2022-07-18 13:47 UTC by MSalopek

Not at all properly tested.

Instead of using the current version, this allows specifying VALUE length > 256 (currently unbounded, but has to be < 65535).

2022-07-19 22:19 UTC, maevyn11 requested changes
Hey overall looks really good. Think you're on the right track. Left a couple questions on the error handling in parsePrefix. Not sure if I spotted a potential bug or if I'm missing something about the implementation. Otherwise, mostly just suggestions to clarify a few things and for testing.

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv.go
> +		if len(b)-1 <= 0 {
would it be just as correct to code it this way? 
```
if len(b) != 2 {
return err...
}
``` 
If so I think it's a bit more clear what the check is. Took me a minute to figure out what this was doing.

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv.go
> +		if len(b)-2 <= 0 {
Same question as on the above check. 
```
if len(b) != 3
```

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv.go
> +	// used for TLV.Value lengths between 128 and 255
thanks for the comments, very helpful.

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv.go
> +		if len(b)-1 <= 0 {
Also, how does this check work when the data passed in is the entire payload for a command. Since it may consist of a group of TLVs, couldn't the length of b be anything? Or am I missing something?

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv.go
> +	}
Nice, I like the new approach with parsePrefix and then seeking to read the value. Very clean. More readable than my old looping implementation above. Probably more efficient too.

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv_test.go
> +	}
Guessing you had this in mind for later but we'll want to check a bunch of additional cases, including using constructedTags, packets at and in between each length boundary, packets that exceed the max size extended, and invalid packets.

2022-07-19 22:19 UTC, maevyn11 commented on tlv/tlv_test.go
> +	}
The card implementation is being developed by @SecureElement at the same time, so we can get some sample output from the new extended BERTLV implementation there when it's ready and plug it in here to make sure they're in accordance.

2022-07-20 07:28 UTC, MSalopek commented on tlv/tlv_test.go
> +	}
Having some examples would be awesome.

If we can get some soon, I'd like to use them for table tests.

There will be some basic sanity check tests that check if the prefix parsing is working as expected.

2022-07-20 07:33 UTC, MSalopek commented on tlv/tlv.go
> +func ParseBERTLVPacket(data []byte, constructedTags ...byte) (TLVCollection, error) {
True, that's just for testing and showcasing development. If I change the name, all the tests in the code will fail, and all the parsing and TLV building will fail.

2022-07-20 07:33 UTC, MSalopek commented on tlv/tlv.go
> +- CASE LENGTH > 0x7f (127) -> LENGTH encoded using 2 bytes
That is correct. The comment is wrong. It should be as you stated (`case LENGTH > 0x7f (127) and LENGTH <= 0xFF (256)`)

2022-07-20 08:22 UTC, MSalopek commented on tlv/tlv.go
> +		if len(b)-1 <= 0 {
There is a bug in the code, yes :D Thank you for finding it.

The func `parsePrefix` takes the full TLV and checks the start bytes because you cannot know how long the prefix is unless you peek into the slice - the `Tag-Length` part of TLV can be 2 to 4 bytes long.

Just slicing the TLV with data[0:4] would panic in case  len(TLV) < 4 - which is a valid TLV with only the TAG and a single LENGTH byte that should be set to 0  (TLV with 0 length value), or a TLV that has a single VALUE byte.

The initial intention was the following:
- check that the bytes defining the length are in the correct position from the start of the array
- if you subtract the byte position from the prefix length and end up with a negative value, something is wrong

The parsing was updated with regards to your comments.
```golang
func parsePrefix(b []byte) (byte, int, int, error) {
	if len(b) == 0 {
		return 0, 0, 0, errors.New("prefix not provided")
	}

	if len(b) < 2 {
		return 0, 0, 0, errors.New("prefix too short")
	}

	tag := b[0]

	if b[1] <= 0x7F {
		return tag, int(b[1]), 2, nil
	}

	if b[1] == 0x81 {
		if len(b) < 3 {
			// TLV too short to encode 2 length bytes (TAG+2 LENGTH bytes)
			return 0, 0, 0, errors.New("invalid TLV - expected 2 bytes length encoding")
		}
		return tag, int(b[2]), 3, nil
	}

	if b[1] == 0x82 {
		if len(b) < 4 {
			// TLV too short to encode 3 length bytes (TAG+3 LENGTH bytes)
			return 0, 0, 0, errors.New("invalid TLV - expected 3 bytes length encoding")
		}
		return tag, int(binary.BigEndian.Uint16(b[2:4])), 4, nil
	}

	return 0, 0, 0, errors.New("invalid value prefix encoding")
}
```

2022-07-20 08:23 UTC, MSalopek commented on tlv/tlv.go
> +		if len(b)-2 <= 0 {
Added answer above. The function takes the full TLV as argument, so instead of checking inequality it checks if the overall length is less than required minimal length.

2022-07-20 08:23 UTC, MSalopek commented
It would be nice to have 5-6 examples for testing.

2022-07-21 21:13 UTC, maevyn11 commented on tlv/tlv.go
> +func ParseBERTLVPacket(data []byte, constructedTags ...byte) (TLVCollection, error) {
👍

2022-07-21 21:25 UTC, maevyn11 requested changes
Couple follow up comments on the changes

2022-07-21 21:25 UTC, maevyn11 commented on tlv/tlv.go
> +	tag, length, seek, err := parsePrefix(data[0:4])
Possibly panic on the slice here if the packet is only 3 bytes long? (1 byte tag, 1 byte length, 1 byte value) could be a valid TLV. May have to put a guard above to check the length and pass in a smaller slice if the data is less than 4 bytes longs.

2022-07-21 21:25 UTC, maevyn11 commented on tlv/tlv.go
> +	// due to some smart contract restrictions
It's note exactly due to smart contract restrictions, but mainly to make the encoding more efficient for interacting with the resource constrained smart card.

2022-07-21 21:25 UTC, maevyn11 commented on tlv/tlv.go
>  		return tag, int(binary.BigEndian.Uint16(b[2:4])), 4, nil
May need to check on the maximum value that can be encoded here and ensure it's not more than the card can handle. I'm not exactly sure what the upper limit is. Maybe @SecureElement can give the exact value here when he's available. (He's out on vacation until Monday)

2022-07-21 21:26 UTC, maevyn11 commented on tlv/tlv.go
> +	tag, length, seek, err := parsePrefix(data[0:4])
Think this does fix parsePrefix's byte logic though.

2022-07-21 21:28 UTC, maevyn11 commented on tlv/tlv.go
> +		if len(b)-1 <= 0 {
Nice, yes I think this fixes the issue. I would add a check at the top that len(b) <= 4, as otherwise we can't guarantee that the caller will always obey the rules and restrict the input length.

2022-07-21 21:28 UTC, maevyn11 commented on tlv/tlv.go
> +- CASE LENGTH > 0x7f (127) -> LENGTH encoded using 2 bytes
👍

2022-07-21 21:36 UTC, maevyn11 commented on tlv/tlv_test.go
> +	}
Here's an example APDU. An APDU always has a header of 4 bytes and then is followed by the data. Normally that data is TLV encoded but there are a few commands inherited from the upstream codebase which don't encode in TLV format. 
APDU:
```
0032000030D0582F4568171AC5A8375F100AE6B7CF951A4296E68B37EA6B33919528FDD7D42C16981DC2A14957AEC919F1E654922C
```
TLV (first 4 bytes removed): 
```
30D0582F4568171AC5A8375F100AE6B7CF951A4296E68B37EA6B33919528FDD7D42C16981DC2A14957AEC919F1E654922C
```

You can actually generate these yourself fairly easily. As long as the app's log level is Debug it will automatically generate an `apdu.log` file in the root of the project whenever the cli is invoked. This will include all the APDU's launched in that session, which you can manually parse the TLV's out of to generate test cases. 

An example of running the cli: 
```
go run main/phonon.go createPhonon 1
```

These aren't perfect for this as they are commands instead of responses, but they should contain valid TLV's for testing. We'll have to get some sample output from the new card changes to get some that are sufficiently long to test the extended length aspect, but the existing ones should work well for regression testing.

2022-07-21 21:37 UTC, maevyn11 commented on tlv/tlv_test.go
> +	}
Let me know if you have any trouble generating these, not sure if it'll work right without a card available. We can generate some for you to use if so.

2022-07-25 10:27 UTC, MSalopek commented on tlv/tlv.go
> +	// due to some smart contract restrictions
Meant to write "smart card", and wrote "smart contract". Too many things are smart these days :D

2022-07-25 17:11 UTC, SecureElement commented
> Not at all properly tested.
> 
> Instead of using the current version, this allows specifying VALUE length > 256 (currently unbounded, but has to be < 65535).

The maximum ( for now ) is 32K ( 0x7fff ) in Javacard.  We should max this a static variable that can be changed as needed.  RIght now,  it should be set to the maximum size that the secure channel can handle ( around 200 bytes ).

2022-07-25 17:13 UTC, SecureElement commented
unencrypted BerTLV sample 
80510000#(90819030900202000080410468F84EC5BF0B5F4EB94ED720EF99FC1EFA4FECE6EA9B9138C3F4C07E169C0940DBF9128BD9ABAB58E8B8AEAA9F6313AEB9D17B05E37201FD68201F4AEB675903304502205AA91139AA469435F5F5EE3D18E333276C97F39792D02300D1DB89D89853EC2002210090AD60F5767B1A62FD91054B48DCBAE5CEA7B469349993A4C2A38698D92A3BE9\
912096DC0119296C3C2236E5146A72BCBD284CE68535727A43C2B784B378CB243C21)
the pound sign signifies Lc where the script calculates the length of data being sent and places it there.  Will include a few more examples

2022-07-25 17:14 UTC, SecureElement commented
80530000#(93473045022100C7DC911449F799FAD2F2522D2CDFF88B69A4BFFABC4D90A734454BAA63CE28AE0220128B78E3C1EA07F1B9CB84D38DA8BF6EC64F107EE73ED78275EEF9A6691BB7E1)

2022-07-25 17:15 UTC, SecureElement commented
80500000#{908191309102020000804104D2B04AE13EE4D991A94065009DC7C0C48620663FB8B5C8F3890FF53F00CA7D5148BFAD218922E076E30AB8DC1509C7CF1296772EEAC37F8C7A7180920CD908503046022100FD12CCA7BFA3139FF383B655B6018811042D2654DF5C2F56A00B9951A67824A602210080F8C336A5DF1205FA1B732512126B4C0370BB41E175F897363D5659BEB54CA0}

2022-07-25 17:15 UTC, SecureElement commented
/send 80520000#(912015FB87F3577AC358E209EED7316C6EDB96981E04B4ED7E5DF597677B0B90BC2B921058EAE71460719CF332C9206863BD50F093473045022100C67639FA671CCCFC91B8A0CBFFFF5553EFBDC143933170C7129C48A42B45E3BE02204B12629A498DF0974E6B9DA4F915DC0C64D4C07E9C167E2FFA354B2888B9F79C)

2022-09-03 19:15 UTC, MSalopek commented on tlv/tlv.go
> +	tag, length, seek, err := parsePrefix(data[0:4])
Func was removed, so not relevant any more.

2022-09-03 19:15 UTC, MSalopek commented on tlv/tlv.go
> +		if len(b)-1 <= 0 {
To continue the discussion, I actually removed `parsePrefix` function. The parsing is done in a for loop, similar to how it was done in the  previous TLV parser.

I also removed the things that made the doce look nice, because they were making the code more difficult to understand, but looked a lot prettier.

2022-09-27 18:27 UTC, closed without merging