Friendly name (#110)
GridPlus/phonon-client pull request #169
Opened 2022-07-19 18:40 UTC by zerodouglas

Renames GetName to GetCardId. I added two new functions to the session interface so that the new resources to appropriately be called and added necessary changes to Swagger.

2022-07-19 18:45 UTC, npmaile requested changes
You've done precisely what I wanted. Good work. You just need to change a couple of things around the http semantics and error messaging

2022-07-19 18:45 UTC, npmaile commented on gui/api.go
> +	r.HandleFunc("/cards/{sessionID}/name", session.name)
just have the one endpoint of '/cards/{sessionID}/name'
use the verb to determine what to do. A GET should retrieve the name and a Post should set/overwrite the name

2022-07-19 18:45 UTC, npmaile commented on gui/api.go
> +		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
just do a statusInternalServerError here though unprocessable entity may be more correct, but we would need to parse the error here to determine the precise issue before giving a more specific error response

2022-07-19 18:45 UTC, npmaile commented on gui/api.go
> +		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
same complaint as above

2022-07-19 18:45 UTC, npmaile commented on gui/api.go
> +		http.Error(w, "No friendly name found", http.StatusNotFound)
after the change to cardID for the card's id, you can refer to the friendly name as "name"

2022-07-19 19:56 UTC, maevyn11 commented on gui/api.go
> +func (apiSession apiSession) createName(w http.ResponseWriter, r *http.Request) {
I'd prefer setName or setFriendlyName for this function. create implies a new name is being created, but this call could also change an existing friendly name setting.

2022-07-19 19:57 UTC, maevyn11 commented on gui/api.go
> +func (apiSession apiSession) name(w http.ResponseWriter, r *http.Request) {
Would prefer getName or getFriendlyName for this to make it clear from outside what it's doing.

2022-07-19 20:08 UTC, zerodouglas commented on gui/api.go
> +func (apiSession apiSession) name(w http.ResponseWriter, r *http.Request) {
I suppose `getFriendlyName` is more clear about it's function.

2022-07-19 20:10 UTC, zerodouglas commented on gui/api.go
> +func (apiSession apiSession) createName(w http.ResponseWriter, r *http.Request) {
I agree, I'll change to `setFriendlyName` to inline with `getFriendlyName`.

2022-07-19 20:17 UTC, zerodouglas commented on gui/api.go
> +		http.Error(w, "No friendly name found", http.StatusNotFound)
Sure, I'll get that changed to `sess.GetFriendName()` to `sess.GetName()` and `sess.SetName()`.

2022-07-19 20:32 UTC, maevyn11 commented on gui/swagger.yaml
> +        "500":
If you change the error code in the handler make sure this response code matches

2022-07-20 15:11 UTC, douglance commented
Testing this out with swagger, it seems that after renaming a card, then calling `/listSessions` the `phonon-client` returns each session's original name, rather than the name it has been renamed to. The frontend will have to make another request for each session, which isn't a big deal; but we have two things with the same name. This seems a bit confusing. 

I would like to propose having `/listSessions` return `Id` as the initial identifier and `Name` as a string of it's friendly name or an empty string if it isn't set (it could also just be absent if not set).

So the change would be from 
```json
[{"Name":"043bf3fe28725a70","Initialized":true,"TerminalPaired":true,"PinVerified":true}]
```
to:
```json
[{"Id":"043bf3fe28725a70","Name":"Friendly","Initialized":true,"TerminalPaired":true,"PinVerified":true}]
```
or:
```json
[{"Id":"043bf3fe28725a70","Name":"","Initialized":true,"TerminalPaired":true,"PinVerified":true}]
```

2022-07-20 15:36 UTC, zerodouglas commented
> Testing this out with swagger, it seems that after renaming a card, then calling `/listSessions` the `phonon-client` returns each session's original name, rather than the name it has been renamed to. The frontend will have to make another request for each session, which isn't a big deal; but we have two things with the same name. This seems a bit confusing.
> 
> I would like to propose having `/listSessions` return `Id` as the initial identifier and `Name` as a string of it's friendly name or an empty string if it isn't set (it could also just be absent if not set).
> 
> So the change would be from
> 
> ```json
> [{"Name":"043bf3fe28725a70","Initialized":true,"TerminalPaired":true,"PinVerified":true}]
> ```
> 
> to:
> 
> ```json
> [{"Id":"043bf3fe28725a70","Name":"Friendly","Initialized":true,"TerminalPaired":true,"PinVerified":true}]
> ```
> 
> or:
> 
> ```json
> [{"Id":"043bf3fe28725a70","Name":"","Initialized":true,"TerminalPaired":true,"PinVerified":true}]
> ```
> 
> This would also make more sense with the naming of `GetCardId()` (if I understand the changes correctly (I do not write Go)).

I think this makes sense and not a hard feature to implement. @npmaile @maevyn11 should we cut the function to only act as a POST in this case?

2022-07-20 17:11 UTC, maevyn11 commented
Agree with @douglance 's suggestions as to renaming the fields passed to the frontend to disambiguate CardId and Name, passing both when available. 

Not sure what you mean by this? 

> should we cut the function to only act as a POST in this case?

Is the idea that the GET is unnecessary because the name will now be retrieved instead by /listSessions? 

I'm on board with that if so, better to have that functionality encapsulated in one place, but it does mean you'll need to ensure that the friendlyName will always have to be pulled into the session when it's available, so this call may need to be added to the session initialization sequence to ensure it's consistently cached in the client.

2022-07-20 18:03 UTC, zerodouglas commented
> Agree with @douglance 's suggestions as to renaming the fields passed to the frontend to disambiguate CardId and Name, passing both when available.
> 
> Not sure what you mean by this?
> 
> > should we cut the function to only act as a POST in this case?
> 
> Is the idea that the GET is unnecessary because the name will now be retrieved instead by /listSessions?
> 
> I'm on board with that if so, better to have that functionality encapsulated in one place, but it does mean you'll need to ensure that the friendlyName will always have to be pulled into the session when it's available, so this call may need to be added to the session initialization sequence to ensure it's consistently cached in the client.

Yes, I had removed the GET request endpoint as it's now retrieved via /listSessions. I just made the changes to support your suggestion. The call will specifically return it from the session sequence.

2022-07-21 21:10 UTC, maevyn11 commented
All the code in the new changes looks good, but I think we should get the corresponding phonon-app changes committed to the submodule before merging, that way master will continue to function through the merge of the PR. https://github.com/GridPlus/phonon-app/pull/31 

Also conflicts with the other recent PRs need to be resolved before this one can merge.

2022-07-22 19:51 UTC, maevyn11 approved these changes
Tried it out and it works for me. Nicely done

2022-07-22 20:00 UTC, npmaile commented
fix merge conflicts and ill test again and approve

2022-07-22 20:16 UTC, npmaile commented
> fix merge conflicts and ill test again and approve

disregard. Force merging because I'll fix ci in a few minutes

2022-07-22 20:17 UTC, merged