fix all linter errors in go files
GridPlus/phonon-client pull request #179
Opened 2022-07-25 20:52 UTC by npmaile

updates to each of the go files to make the gopls linter stop complaining. The fixes are including but not limited to the following:
1. lowercasing error messages
2. turning long if/else statements into switch case
3. assigning unused identifiers to the "_" sink
4. removing unnecessary sprint statements

2022-07-25 22:41 UTC, maevyn11 requested changes
Thanks for doing this, few minor comments and it should be good to go.

2022-07-25 22:41 UTC, maevyn11 commented on card/apdu.go
> +			SW_INCORRECT_P1P2:           errors.New("incorrect Parameters received"),
"Parameters should be lowercased too.

2022-07-25 22:41 UTC, maevyn11 commented on card/apdu.go
> +			SW_WRONG_DATA:               errors.New("unable to decode Phonon key list TLV"),
"Phonon" should be lowercased

2022-07-25 22:41 UTC, maevyn11 commented on card/apdu.go
> +			SW_WRONG_DATA + 2:           errors.New("unable to read Signature TLV"),
"Signature" caps

2022-07-25 22:41 UTC, maevyn11 commented on card/apdu.go
> +			SW_WRONG_DATA:                    errors.New("unable to read Receiver signature TLV"),
"Receiver" caps

2022-07-25 22:41 UTC, maevyn11 commented on card/apdu.go
> +			SW_LOGICAL_CHANNEL_NOT_SUPPORTED: errors.New("already Mutually Authenticated"),
"Mutually Authenticated" caps

2022-07-25 22:41 UTC, maevyn11 commented on card/phononCommandSet_test.go
> +		{model.Ethereum, model.Denomination{Base: 1, Exponent: 0}},
Nice

2022-07-25 22:41 UTC, maevyn11 commented on card/phononCommandSet_test.go
> +		keyIndex, _, err = cs.CreatePhonon(model.Secp256k1)
why this change? Isn't this equivalent?

2022-07-25 22:41 UTC, maevyn11 commented on card/phononCommandSet_test.go
> +		keyIndex, _, err = cs.CreatePhonon(model.Secp256k1)
old way seems cleaner to me.

2022-07-25 22:41 UTC, maevyn11 commented on cert/cert.go
> +	key.X, key.Y = key.ScalarBaseMult(key.D.Bytes())
We sure this is equivalent? I guess we're accessing the embedded fields here, but doing it explicitly on the public key seems more clear, whereas now I'm not sure if Curve is at the top level, or in the private key, or the public key or some combination.

2022-07-25 22:41 UTC, maevyn11 commented on cert/cert.go
> +		return CardCertificate{}, errors.New("card Certificate Invalid")
caps on the last two words

2022-07-25 22:41 UTC, maevyn11 commented on util/crypto.go
> +
This is a nice change but it scares me a bit since it touches crypto parsing which could be hard to debug from outside. Is there a unit test to regression test this still works the same?

2022-07-25 22:42 UTC, npmaile commented on card/phononCommandSet_test.go
> +		keyIndex, _, err = cs.CreatePhonon(model.Secp256k1)
it was mad because err was shaddowed. This is more explicit. 
I really just don't like the linter complaining

2022-07-25 22:52 UTC, npmaile commented on cert/cert.go
> +	key.X, key.Y = key.ScalarBaseMult(key.D.Bytes())
yes. the private key (according to the go implementation of the ecdsa library) consists of an embedded public key and a D field.

2022-07-25 23:10 UTC, npmaile commented on cert/cert.go
> +	key.X, key.Y = key.ScalarBaseMult(key.D.Bytes())
https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/crypto/ecdsa/ecdsa.go;drc=8384fe86a5b7f579a50c7ad423d4dd4eb2d1f117;l=80

2022-07-26 03:02 UTC, npmaile commented on util/crypto.go
> +
there is a unit test, and it does pass.

2022-07-26 22:11 UTC, maevyn11 approved these changes
Looks great

2022-07-26 22:12 UTC, merged