Move cache
GridPlus/phonon-client pull request #180
Opened 2022-07-25 23:36 UTC by zerodouglas

Migrated cache out of the API and into the orchestrator. Resolves numerous issues such as #170. I did test the functionality, you can indeed create a phonon with the proper chain id, pair cards and send to that card id as well as redeeming.

2022-07-26 17:29 UTC, npmaile requested changes
s.friendlyName is already the cached friendly name. I forgot to remove cachedFriendlyName from the struct after I erroneusly added it not realizing the existing friendly name field was already a cache.

2022-07-26 17:30 UTC, npmaile commented on orchestrator/session.go
> +		return s.cachedFriendlyName, nil
need to change this reference to friendlyName

2022-07-26 17:30 UTC, npmaile commented on orchestrator/session.go
> +		s.cachedFriendlyName = s.friendlyName
this isn't necessary

2022-07-26 17:48 UTC, zerodouglas commented on orchestrator/session.go
> +		return s.cachedFriendlyName, nil
> s.friendlyName is already the cached friendly name. I forgot to remove cachedFriendlyName from the struct after I erroneusly added it not realizing the existing friendly name field was already a cache.

Makes more sense, I wasn't sure of the use for cachedFriendlyName

2022-07-27 19:57 UTC, maevyn11 reviewed
Just asked for clarification on a couple elements of the design. Can probably go in as is once we clear those up.

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +	return s.friendlyName, nil
This is to fix the missing friendlyName on startup right? Pattern becomes the same as GetCardID() where it will run a command to check if the name isn't already cached?

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +	return nil
This is a nice fix to ensure that the name isn't cached if there is an error talking to the card but I think it breaks error handling for SetName(), since this would now always return nil, even if s.cs.SetFriendlyName returns an error. 

changing line 159 to the following would fix. 
```
return err
```

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +	s.cachePopulated = false
cool, was wondering where this happens and this spot makes a lot of sense.

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +/*addPubKeyToCache adds the pubkey to an already cached phonon. This is done differently from the addInfoToCache for reasons.*/
what reasons?

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +	if currencyType == 0 && lessThanValue == 0 && greaterThanValue == 0 {
good check, this comment is for a larger discussion, but now that we have this caching layer to improve performance, I think we may want to ditch the on card filtering entirely for Beta. It's unimplemented anyway, we haven't had a use for it, and it seems to mostly serve to add complexity like this this statement at this point.

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +		cachedPubKey := cached.p.PubKey
Is there any risk that accessing this value here will nil panic, either on p or on pubkey? 

Little confused about the handling of the PubKey value within this function when there is already addPubKeyToCache above? Feel like I'm missing why setting this would be relevant here.

2022-07-27 19:57 UTC, maevyn11 commented on gui/api.go
> +		p.PubKey, err = sess.GetPhononPubKey(p.KeyIndex, p.CurveType)
Not for this PR, but it seems to me that always call GetPhononPubKey along with ListPhonons. Might simplify things to merge these under one higher level Session call or actually merge these into one command on the card for Beta

2022-07-27 19:57 UTC, maevyn11 commented on orchestrator/session.go
> +	infoCached   bool
I don't see pubkeyCached or infoCached being checked anywhere. Only a check on the whole cache with cachePopulated. 

Plans for future expansion with these or is there another reason why they're included?

2022-07-27 20:01 UTC, npmaile commented on orchestrator/session.go
> +	return s.friendlyName, nil
exactly

2022-07-27 20:02 UTC, npmaile commented on orchestrator/session.go
> +	s.cachePopulated = false
:+1:

2022-07-27 20:04 UTC, npmaile commented on orchestrator/session.go
> +		cachedPubKey := cached.p.PubKey
it will set it to nil if it's already nil. the two functions exist so that if we have the pubkey cached and not the rest of the info, we cache the rest of the info without changing the pubkey or asking for it again, and if we have the info cached, but not the pubkey, we can cache the pubkey without changing everything else.

2022-07-27 20:04 UTC, npmaile commented on gui/api.go
> +		p.PubKey, err = sess.GetPhononPubKey(p.KeyIndex, p.CurveType)
that would clear up the above confusion with the cachepubkey vs cachephonon stuff

2022-07-29 19:21 UTC, maevyn11 approved these changes
Code's good to go but left one suggestion to improve a comment.

2022-07-29 19:21 UTC, maevyn11 commented on orchestrator/session.go
> +/*addPubKeyToCache adds the pubkey to an already cached phonon. This is done differently from the addInfoToCache for reasons.*/
should explain the reasons in the comment or remove the mysterious reference. This comment will likely be frustrating to look at in 6 months when we've all forgot the reasons

2022-08-01 19:46 UTC, maevyn11 commented
Hey I checked out the latest version of this branch to test and I the bugs https://github.com/GridPlus/phonon-client/issues/170 and https://github.com/GridPlus/phonon-client/issues/178 still seem to be present for me. Can someone else pull and let me know if you're seeing this or not?

2022-08-01 20:47 UTC, npmaile commented
crap, actions is failing now

2022-08-01 21:39 UTC, npmaile approved these changes

2022-08-01 21:39 UTC, merged