Startup window
GridPlus/phonon-client pull request #195
Opened 2022-08-03 04:53 UTC by npmaile

Window that opens on startup from desktop or optionally when using the command line option to allow for setting the telemetry key

2022-08-04 18:41 UTC, maevyn11 requested changes
Left a review on the code, going to run through the configurator myself and give some design feedback.

2022-08-04 18:41 UTC, maevyn11 commented on cmd/graphicalConfigure.go
> +and usage of using your command. For example:
needs a description so CLI users know what they're looking at.

2022-08-04 18:41 UTC, maevyn11 commented on config/config.go
> +	viper.SetDefault("AppletCACert", string(cert.PhononAlphaCAPubKey))
why is this changed to string? Isn't AppletCACert asking for a []byte?

2022-08-04 18:41 UTC, maevyn11 commented on config/graphical.go
> +	welcome := widget.NewLabel("Welcome to Phonon configuration. Please paste your alpha logging key here")
key is referred to as "Telemetry Key" below, I would stick with the same name in all the user facing text to avoid confusion. Suggest "Please paste your telemetry key here"

2022-08-04 18:41 UTC, maevyn11 commented on config/graphical.go
> +}
I think this function belongs in the Config package where it can be reused. Also LoadConfig() and this should derive the homedir in the same way so they can't get out of sync. Suggest factoring out the homedir detection and directory creation into one or two other functions called by SaveConfig and LoadConfig

2022-08-04 18:41 UTC, maevyn11 commented on release/MacOS/Phonon.app/Contents/MacOS/phonon-launcher
> +	echo "e"
assume these echo statements are for debugging and should be removed before merge?

2022-08-04 18:41 UTC, maevyn11 commented on release/MacOS/Phonon.app/Contents/MacOS/phonon-launcher
> +	if ! [ -f "$HOME/.phonon/phonon.yml" ] ; then
Can this check the telemetry key test endpoint instead of checking for the config file like we discussed? 

Otherwise this would have to account for the alternate config files supported within Viper's config setup.

2022-08-04 18:45 UTC, npmaile commented on config/graphical.go
> +}
it is in the config package

2022-08-04 18:45 UTC, npmaile commented on release/MacOS/Phonon.app/Contents/MacOS/phonon-launcher
> +	echo "e"
correct

2022-08-04 18:47 UTC, maevyn11 commented on config/graphical.go
> +				welcome.SetText(fmt.Sprintf("Telemetry key validation failed: %s", err.Error()))
I don't seem to be able to get this error to show

2022-08-04 18:47 UTC, maevyn11 commented on config/graphical.go
> +			}
Should be some confirmation text for the user when the logging key test succeeds.

2022-08-04 18:48 UTC, npmaile commented on release/MacOS/Phonon.app/Contents/MacOS/phonon-launcher
> +	if ! [ -f "$HOME/.phonon/phonon.yml" ] ; then
not really. I'm assuming graphical users will not want to use an alternative config path, and if the check fails here, the application will fail to launch. the endpoint check will happen when it's being configured and in the app. The launcher really shouldn't be making calls to the network, and there's not really any way to notify the user of what's going on if it fails

2022-08-04 18:50 UTC, maevyn11 commented on config/graphical.go
> +}
right...didn't realize that at the time. Guess I expected it to be in config.go because this doesn't specifically pertain to the graphical frontend configurator.

2022-08-04 18:51 UTC, maevyn11 commented on config/graphical.go
> +				welcome.SetText(fmt.Sprintf("Telemetry key validation failed: %s", err.Error()))
nvm. I can get it to show, I just didn't realize that lack of output meant it was succeeding.

2022-08-04 18:57 UTC, maevyn11 requested changes

2022-08-04 18:57 UTC, maevyn11 commented on config/graphical.go
> +			cleaned := strings.Trim(keyBox.Text, `\ `)
If you open the graphicalConfigure dialog and you already have a key configured in the config file, but you don't paste it into the box, clicking this test returns an error for "no auth given." 

Ideally if a config key is already present, the test button will use that one. Maybe if the logging key input box is empty we can look in the existing config for a key to check, and return the check results based on that? 

In fact, we could drop the "Save Configuration" button, and only save the config when there has been a confirmed sucessful test of the logging key. I'm concerned some users will hit test but then skip hitting "Save" and not realize no config file has been written.

2022-08-04 19:02 UTC, maevyn11 commented on release/MacOS/Phonon.app/Contents/MacOS/phonon-launcher
> +	if ! [ -f "$HOME/.phonon/phonon.yml" ] ; then
right makes sense. Yea network call here is a bad idea. 

This could cause problems for users who use both the GUI and the CLI and have an alternate config path, but we could fix that by replicating alternate config files into the "standard config location" Not a big deal for now as that will be an unlikely scenario, and we can cross that bridge when we actually encounter the problem.

2022-08-04 20:25 UTC, maevyn11 commented
UI looks pretty good design wise. Idk what options exist in this dialog library, but if it could use the phonon brand colors to match more or less the frontend colors that'd be slick. 

Only other suggestion would be to drop the "Save Configuration". button and combine that workflow into one step with a successful test also saving the config, like I suggested in another comment.

2022-08-16 17:13 UTC, maevyn11 requested changes

2022-08-16 17:13 UTC, maevyn11 commented on config/config.go
> +}
Something in this config save is writing the appletcacert key as a decimal list that looks like this: 
```
appletcacert:
- 4
- 114
- 213
- 140
- 30
- 196
- 143
...
```
This should really be changed so we're just saving the "dev" or "alpha" config key and the appletcacert variable is not written to the config file.

2022-08-17 17:21 UTC, npmaile commented
tested and working on windows and linux

2022-08-17 17:24 UTC, npmaile commented on config/config.go
> +	viper.SetDefault("AppletCACert", string(cert.PhononAlphaCAPubKey))
fixed

2022-08-17 19:51 UTC, maevyn11 approved these changes
Looks good!

2022-08-17 19:53 UTC, merged