Added EVM tokens and a gas fee check
GridPlus/phonon-client pull request #198
Opened 2022-08-04 20:50 UTC by zerodouglas

Adds Binance, Avalanche, and Polygon. It's to note that they will fail if the gas fee is too low for redemption, for this I added a small check to display to the gui exactly when this fails for the legacy transaction. I did test each and every and they do work as intended. Some of these tokens offers multiple RPC nodes such as Binance, however, I just stuck with the first one they provided.

2022-08-04 21:18 UTC, maevyn11 commented
Do you happen to have some instructions or handy links for adding all these networks to Metamask? Would be good to provide to the DAO to include with the testnet instructions.

2022-08-04 21:22 UTC, zerodouglas commented
Sure! Here are tutorials for MetaMask
- Binance Smart Chain [Binance MM](https://support.binance.us/hc/en-us/articles/4423865255319-Configuring-MetaMask-with-Binance-Smart-Chain)
- Avalanche [Avalanche MM](https://medium.com/seedify/how-to-add-an-avalanche-c-chain-rpc-to-metamask-e8f08979a8a8)
- Polygon [Polygon MM](https://www.coincarp.com/chainlist/mumbai/)

2022-08-04 21:25 UTC, zerodouglas commented
Here are faucets as well.

- Binance Smart Chain [Binance Faucet](https://testnet.binance.org/faucet-smart)
- Matic [Mumbai Faucet](https://mumbaifaucet.com/)
- Avalanche [Avalanche Faucet](https://faucet.avax.network/)

2022-08-04 21:31 UTC, zerodouglas commented
I should probably note that I personally was using chain ID 43113 for AVAX on my MetaMask rather than 43114. I see that the tutorial that I provided uses 43114 and so does the phonon-app. I didn't have any issues but I made the change to align with phonon-app.

2022-08-04 21:56 UTC, maevyn11 requested changes
Confirmed working for me with at least AVAX testnet

2022-08-04 21:56 UTC, maevyn11 commented on chain/ethChainService.go
> +	case 97: // Binance
Would change comment to // Binance Testnet

2022-08-04 21:56 UTC, maevyn11 commented on chain/ethChainService.go
> +	case 43113: // Avalanche
similarly, could use a comment on which testnet this endpoint points to, seems like there are a bunch of different ones.

2022-08-04 21:56 UTC, maevyn11 commented on chain/ethChainService.go
> +	case 80001: // Polygon
Same as above for this comment

2022-08-04 21:56 UTC, maevyn11 commented on chain/ethChainService.go
> +		log.Error("balance is insufficient to cover redemption value")
think this should say. Balance is insufficient to cover gas cost of redemption.

2022-08-04 21:56 UTC, maevyn11 commented on chain/ethChainService.go
> +	}
Actually isn't this whole check redundant with the parent function redeemPhonon starting with the block at line 65? 
```
	//Collect on chain details for redeem
	nonce, onChainBalance, suggestedGasPrice, err := eth.fetchPreTransactionInfo(ctx, common.HexToAddress(p.Address))
	if err != nil {
		return "", err
	}
	redeemValue := eth.calcRedemptionValue(onChainBalance, suggestedGasPrice)
	log.Debug("transaction redemption value is: ", redeemValue)
	//If gas would cost more than the value in the phonon, return error
	if suggestedGasPrice.Cmp(onChainBalance) != -1 {
		log.Error("phonon not large enough to pay gas for redemption")
		return "", errors.New("phonon not large enough to pay gas for redemption")
	}
	tx, err := eth.submitLegacyTransaction(ctx, nonce, big.NewInt(int64(p.ChainID)), common.HexToAddress(redeemAddress), redeemValue, eth.gasLimit, suggestedGasPrice, privKey)
	if err != nil {
		return "", err
	}
```

2022-08-04 21:56 UTC, maevyn11 commented on chain/ethChainService.go
> +	}
Think this can probably be dropped since this is already handled in fetchPreTransaction issue and not called anywhere if the below check is dropped.

2022-08-04 21:56 UTC, maevyn11 commented on gui/api.go
> +	}
since the above may loop through several redeems, I think this error check will only catch an error in the last redeem. 

Changing the response status code when there is an error is a good idea, but this should probably still respect the response format and send back the resps slice, which already includes an err field, especially because it could include some successful or partially successful responses. Then again, the error handling for this route is pretty ugly anyway, so maybe this makes no functional difference.  

Maybe 
```
success := true
for _, res := range resps {
  if res.err != nil {
    success = false 
  }
 }
 if !success{
 ...encode with an error status code
 }

2022-08-04 23:03 UTC, zerodouglas commented on chain/ethChainService.go
> +	}
Yes, you're right. I added this because on line 65, it seems to work well for ETH chains only. When I attempt the same test on say Polygon, I receive "rlp: cannot encode negative *big.Int".

2022-08-04 23:11 UTC, zerodouglas commented on chain/ethChainService.go
> +	case 97: // Binance
Changes made at https://github.com/GridPlus/phonon-client/blob/2f7e312ad4b0cb026611e2f8eefbc960aecf7286/chain/ethChainService.go#L140

2022-08-04 23:12 UTC, zerodouglas commented on chain/ethChainService.go
> +	case 43113: // Avalanche
I named them based on their RPC node name, would this be better? https://github.com/GridPlus/phonon-client/blob/2f7e312ad4b0cb026611e2f8eefbc960aecf7286/chain/ethChainService.go#L142

2022-08-04 23:13 UTC, zerodouglas commented on chain/ethChainService.go
> +		log.Error("balance is insufficient to cover redemption value")
I made this change but I'm still curious about my question in response to yours. https://github.com/GridPlus/phonon-client/blob/2f7e312ad4b0cb026611e2f8eefbc960aecf7286/chain/ethChainService.go#L221

2022-08-04 23:14 UTC, zerodouglas commented on gui/api.go
> +	}
That's a great idea and I totally agree. The change is at: https://github.com/GridPlus/phonon-client/blob/2f7e312ad4b0cb026611e2f8eefbc960aecf7286/gui/api.go#L364

2022-08-05 14:47 UTC, maevyn11 commented on chain/ethChainService.go
> +	}
Thought that was just due to the phonon balance having not been high enough?

2022-08-05 15:36 UTC, maevyn11 commented on chain/ethChainService.go
> +	case 97: // Binance
Looks good. And I appreciate the line link

2022-08-05 15:36 UTC, maevyn11 commented on chain/ethChainService.go
> +	case 43113: // Avalanche
perfect

2022-08-05 15:41 UTC, maevyn11 requested changes

2022-08-05 15:41 UTC, maevyn11 commented on gui/api.go
> +	if !success {
This will still only send back the last error, although it now detects errors better. This should ideally encode and send the whole resps as in enc.Encode() below but set the status code to http.StatusInternal error if !success

2022-08-09 22:32 UTC, zerodouglas commented on gui/api.go
> +	if !success {
Changes for this begin at https://github.com/GridPlus/phonon-client/blob/847ba4d15d383cf8a2faac8dc4530601fd428d8a/gui/api.go#L345

2022-08-09 22:36 UTC, zerodouglas commented
Fantom Testnet information as follows:

- [MetaMask Tutorial](https://docs.fantom.foundation/tutorials/set-up-metamask)
- [Faucet](https://faucet.fantom.network)

note* Has been added into the phonon-app.

2022-08-10 15:44 UTC, maevyn11 commented on gui/api.go
> +	}
If there are multiple errors does this append duplicate headers or overwrite them? If the former this should ideally be prevented. 

Also I believe the swagger.yml needs to be updated to reflect this API change. I think the "200" code sections happens to already be unparseable by swagger as well, so that ought to be remedied as well.

2022-08-10 18:12 UTC, zerodouglas commented on gui/api.go
> +	}
Ah I missed this. I wouldn't think you could or want to override them especially in this range. I'll add back the variable to set the boolean as it actually makes big sense. I'll update the swagger now aswell :)

2022-08-10 18:54 UTC, zerodouglas commented on gui/api.go
> +	}
Majority is the random formatting that occurred, otherwise, the changes start at https://github.com/GridPlus/phonon-client/blob/5abf9563ae242bc7071e9f7880ad45f4056ee391/gui/swagger.yaml#L467. You should now be able to get a parsed response.

2022-08-10 19:26 UTC, maevyn11 commented on gui/api.go
> +	}
looks good now

2022-08-10 19:26 UTC, maevyn11 approved these changes
Looks great. Really fun to see this feature working.

2022-08-10 22:03 UTC, merged