Better systray
GridPlus/phonon-client pull request #203
Opened 2022-08-09 19:44 UTC by npmaile

2022-08-09 19:45 UTC, npmaile commented
still tweaking. not quite ready yet.

2022-08-16 17:27 UTC, maevyn11 requested changes

2022-08-16 17:27 UTC, maevyn11 commented on release/MacOS/Phonon.app/Contents/MacOS/phonon-launcher
> +	echo "a"
guessing these echo statements were for debug purposes and can be removed?

2022-08-16 17:27 UTC, maevyn11 commented on config/config.go
> +	viper.SetDefault("AppletCACert", string(cert.PhononAlphaCAPubKey))
Having issues starting the app with my existing config file. I added proper error logging on line 60 of card/phononCommandSet here: 
```
func NewPhononCommandSet(c types.Channel) *PhononCommandSet {
	var err error
	conf, err := config.LoadConfig()
	if err != nil {
		log.Fatal("could not configure PhononCommandSet: ", err)
	}
```
Error I get is this
```
{"level":"fatal","msg":"could not configure PhononCommandSet: 2 error(s) decoding:\n\n* cannot parse 'AppletCACert[0]' as uint: strconv.ParseUint: parsing \"\\x04rՌ\\x1eď\\x00r\\xeb×\\x12\\xa8\\xect\\xe5\\xa4X\\x191\\xd6\\xff嗶E\\x9bF\u003c\\x87\\xfc\\xe1Y\\xb8\\xe1\\xae@Ãͮx\\xaa\\xdf\\xff\\xb0\\x83\\x91|\\x91\\x1c?\\x9du\\xa5\\xf1\\xa9$\\xb6'\\xf1]\\xecQ\": invalid syntax\n* cannot parse 'LogLevel' as uint: strconv.ParseUint: parsing \"debug\": invalid syntax","time":"2022-08-16T12:17:36-05:00"}
```
I'm guessing it has something to do with this line since these are the two new defaults being set here.

2022-08-16 17:27 UTC, maevyn11 commented on config/graphical.go
> +func GraphicalConfiguration() {
Seems to be duplicate changes from the startup window PR? Should I review these here or there? https://github.com/GridPlus/phonon-client/pull/195#pullrequestreview-1074490810

2022-08-16 17:27 UTC, maevyn11 commented on gui/systrayIcon.go
> +func SystrayIcon(kill chan struct{}, port string) (end func()) {
testing this branch on mac I no longer see the systray Icon appearing when I start the webUI. .ico file supposed to work on mac as well or is this a windows specific thing?

2022-08-16 20:30 UTC, closed without merging