Fix api cached pubkeys
GridPlus/phonon-client pull request #205
Opened 2022-08-09 22:14 UTC by maevyn11

Prevented the app from unnecessarily waiting for the API to make a bunch of GET_PHONON_PUB_KEY calls when the keys are already cached. 

Also deleted or downgraded a bunch of pointless or obscure logs.

2022-08-09 22:16 UTC, npmaile approved these changes

2022-08-09 22:16 UTC, npmaile commented on gui/api.go
> +		if p.PubKey == nil {
good catch. I didn't even think about this or notice it.

2022-08-09 22:24 UTC, npmaile requested changes

2022-08-09 22:24 UTC, npmaile commented on chain/ethChainService.go
> +func (eth *EthChainService) IsRedeemable()
no function body. oops

2022-08-10 00:31 UTC, maevyn11 commented on chain/ethChainService.go
> +func (eth *EthChainService) IsRedeemable()
oops. I moved that change to a separate branch, forgot to delete before committing this one. Will remove.

2022-08-10 15:28 UTC, maevyn11 commented on chain/ethChainService.go
> +func (eth *EthChainService) IsRedeemable()
https://github.com/GridPlus/phonon-client/pull/205/commits/580f2a21c8a451a1f576d62237ec6c145639d370

2022-08-10 15:29 UTC, maevyn11 commented on gui/api.go
> +		if p.PubKey == nil {
neither did I until I was sitting waiting for the page to load while 15 GET_PHONON_PUB_KEYS ran :)

2022-08-18 18:36 UTC, npmaile approved these changes

2022-08-18 19:25 UTC, merged