inital mining operation endpoint
GridPlus/phonon-client pull request #210
Opened 2022-08-16 18:25 UTC by zerodouglas

2022-08-17 22:11 UTC, maevyn11 requested changes
Few small issues to cover, and needs the frontend submodule included before merging, but the bones look good.

2022-08-17 22:11 UTC, maevyn11 commented on orchestrator/session.go
> +	defer s.ElementUsageMtex.Unlock()
I think this lock needs to be moved inside of the go func. This defer statement is going to run when the enclosing function (starting on line 170) exits, but the goroutine anonymous function will still be running MineNative in a loop, so I think the lock will released before mining has even really started. 

Ideally this lock would enclose the operation on line 199 s.cs.MineNativePhonon to ensure no other session command can come in and try to communicate with the card in another thread.

2022-08-17 22:11 UTC, maevyn11 commented on orchestrator/session.go
> +				totalTime += elapsed
I think this value may be incorrect? Adding up elapsed on each iteration will repeatedly accumulate the time from every previous loop, basically doublecounting each prior iteration on every new iteration. 

I think `elapsed` is the correct total time here and `totalTime` can just be replaced by it in the report output.

2022-08-17 22:11 UTC, maevyn11 commented on orchestrator/session.go
> +					averageTime := time.Duration(float64(totalTime.Nanoseconds()) / float64(i))
I think average time could be reported in the other two cases as well. It'd just be average time of each iteration so far.

2022-08-17 22:11 UTC, maevyn11 commented on orchestrator/session.go
> +	return s.miningReportStatus, nil
Since this value is initialized to nil this statement could panic. Needs to check `if s.miningReportStatus != nil` or the value needs to be initialized to some reasonable default. Not sure there is a reasonable default in the case that mining hasn't taken place yet so the nil check is probably cleanest.

2022-08-18 02:31 UTC, zerodouglas commented on gui/api.go
> +	w.WriteHeader(http.StatusOK)
I agree. I made that change here https://github.com/GridPlus/phonon-client/blob/a8a58b5610af6fa9e412692e5e275ddadcff4ac2/gui/api.go#L316

2022-08-18 02:32 UTC, zerodouglas commented on orchestrator/session.go
> +	hash                  []byte
Correct. It appears to be unused, I've removed it. https://github.com/GridPlus/phonon-client/blob/a8a58b5610af6fa9e412692e5e275ddadcff4ac2/orchestrator/session.go#L29

2022-08-18 02:33 UTC, zerodouglas commented on orchestrator/session.go
> +	miningReportStatus    *miningReportStatus
I like this name better; refer to the above comment for location of change.

2022-08-18 02:33 UTC, zerodouglas commented on orchestrator/session.go
> +		hash:                  nil,
Removed as well.

2022-08-18 02:35 UTC, zerodouglas commented on orchestrator/session.go
> +	defer s.ElementUsageMtex.Unlock()
Hmm, I missed this one. It does so you've described, I've moved this into the go func and it seems to be resolved, I hope this is what you were referring to. https://github.com/GridPlus/phonon-client/blob/a8a58b5610af6fa9e412692e5e275ddadcff4ac2/orchestrator/session.go#L182

2022-08-18 02:37 UTC, zerodouglas commented on orchestrator/session.go
> +				totalTime += elapsed
I partly understand. It could be the time of day but I went ahead and removed the totalTime and rather instead used elapsed and used the supported methods to make it cleaner. https://github.com/GridPlus/phonon-client/blob/a8a58b5610af6fa9e412692e5e275ddadcff4ac2/orchestrator/session.go#L190

2022-08-18 02:38 UTC, zerodouglas commented on orchestrator/session.go
> +					averageTime := time.Duration(float64(totalTime.Nanoseconds()) / float64(i))
Agree, I've made the change to be in the two other cases!

2022-08-18 02:38 UTC, zerodouglas commented on orchestrator/session.go
> +	return s.miningReportStatus, nil
The endpoint will now return "no mining status report available" if the struct is empty. https://github.com/GridPlus/phonon-client/blob/a8a58b5610af6fa9e412692e5e275ddadcff4ac2/orchestrator/session.go#L152

2022-08-18 19:31 UTC, maevyn11 commented on orchestrator/session.go
> +	defer s.ElementUsageMtex.Unlock()
Yea, actually not exactly what I had in mind but I think your implementation is better. I was thinking of locking and unlocking on each iteration, basically like this within the for loop: 
```
s.ElementusageMtex.Lock()
s.cs.MineNativePhonon
s.ElementUsageMtex.Unlock()
```
Putting it at the top of the anon func with defer is nice though, the lock will be held during the entire mining attempt, so there's no chance of other commands being slipped in between unexpectedly. So yea this is better, nice.

2022-08-18 19:34 UTC, maevyn11 commented on orchestrator/session.go
> +				totalTime += elapsed
Think this looks correct now

2022-08-18 19:41 UTC, maevyn11 reviewed
One open ended question to handle and then I think this is good to go.

2022-08-18 19:41 UTC, maevyn11 commented on orchestrator/session.go
> +	miningStatusReport    map[string][]*miningStatusReport
I think this could just a map to a single MiningStatusReport, instead of a slice. So `map[string]*miningStatusReport` 

This data could grow large pretty quickly when storing a report for each iteration. Unless we want to be able to retrieve reports from prior iterations? Thoughts @italianst4 ?

2022-08-18 20:02 UTC, npmaile commented on orchestrator/session.go
> +	miningStatusReport    map[string][]*miningStatusReport
we should just keep the last status report. No need to store the previous data as we are storing aggregate statistics

2022-08-18 23:43 UTC, npmaile requested changes
I'd drop tiny comments all over the place, but the issue here is that you can't look at past mining reports. The id of the mining reports, and their corresponding reports need to be stored in the gui package. This way, if someone slams the mine button 20 times, they can retrieve the status reports of all twenty mining operations including the eventual hashes from them. assigning an id for each mining attempt(as defined by the user clicking the "mine" button) should happen in the gui package.

2022-08-18 23:43 UTC, npmaile commented on orchestrator/session.go
> +		cancelMiningChan:      make(chan bool),
chan struct{} is smaller by like a bit

2022-08-19 14:34 UTC, zerodouglas commented on orchestrator/session.go
> +	miningStatusReport    map[string][]*miningStatusReport
Results at https://github.com/GridPlus/phonon-client/blob/3ba229ee70798a3e6abf252ec1ab8986d2c6f495/orchestrator/session.go#L49

2022-08-23 19:01 UTC, npmaile commented on orchestrator/session.go
> +				s.miningStatusReport[id] = &miningStatusReport{
I'd probably create one mining Status Report, and then overwrite the fields as the process is going along

2022-08-23 19:01 UTC, npmaile commented on orchestrator/session.go
> +				s.miningStatusReport[id] = &miningStatusReport{
rather than create one fresh each time one is being used
though you then have to have the map point to a concrete miningStatusReport object instead of a pointer because you could get concurrent read while another thread is writing, which would panic.

2022-08-24 13:52 UTC, douglance commented on orchestrator/session.go
> +		cancelMiningChan:      make(chan bool),
the frontend doesn't want to be responsible for uuids (if thats what you mean by id here)

2022-08-24 19:59 UTC, maevyn11 requested changes
Just a few comments on things that could be simplified/clarified and a possible race condition to work out. Overall I think the layout for handling miningAttemptIDs between the Session and the gui API looks really good.

2022-08-24 19:59 UTC, maevyn11 commented on gui/api.go
> +	r.HandleFunc("/cards/{sessionID}/phonon/mineNative/status/{miningSessionID}", session.miningReportStatus)
miningSessionID is a little confusing with sessionID already in existence. Maybe we can use a better distinguished variable name? My ideas below:

miningAttemptID
miningRunID

2022-08-24 19:59 UTC, maevyn11 commented on gui/api.go
> +func sessionFromMiningVars(p map[string]string) (string, error) {
Think this should be renamed "miningSessionIDFromVars" as there are no "mining vars", just path variables we're parsing here. 

Also, is this the cleanest way to parse parameters our of URLs? I genuinely don't know, it just feels like this pattern is a little clunky to add a helper function with redundant error checking every time we parse a variable out of a URL.

2022-08-24 19:59 UTC, maevyn11 commented on gui/api.go
> +		fmt.Println("unable to find mining session")
This should be a log.Error instead of a Println. Generally shouldn't have println anywhere in the codebase outside of terminal UI's

2022-08-24 19:59 UTC, maevyn11 commented on gui/api.go
> +		fmt.Println("unable to find mining session")
oh yea and my apdu.log hack... 😬

2022-08-24 19:59 UTC, maevyn11 commented on gui/swagger.yaml
> +          description: "no session with id"
What situation would lead to each of these errors? Feels like we'd always hit the 500 if this request was made to a card that hasn't mined yet. Maybe this should be one error code?

2022-08-24 19:59 UTC, maevyn11 commented on orchestrator/session.go
> +				s.miningStatusReport[id] = &miningStatusReport{
good point. Apparently the semantics around concurrent read/write to maps has changed since go 1.6. TLDR it used to be safe to have just one writer and as many concurrent readers as you wanted, but now it's not. https://stackoverflow.com/questions/36167200/how-safe-are-golang-maps-for-concurrent-read-write-operations 

Seems like the proper way to do this now is to use a thread safe map from the sync package. See here: https://golangprojectstructure.com/maps-thread-safe-goroutine-concurrency/

The way this currently works I think we'll get rare inconsistent results, like undefined behavior when reading the status as another attempt is being written, and possibly panics, so think we need to resolve this.

2022-08-24 19:59 UTC, maevyn11 commented on orchestrator/session.go
> +						if p.KeyIndex == keyIndex {
This change to check the keyIndex looks good, but I think you still have to call GetPhononPubkey and assign the pubkey or the frontend won't be able to see the pubkey/hash. 

```
pubkey, err := s.cs.GetPhononPubKey()
p.PubKey = pubkey
```

2022-08-24 19:59 UTC, maevyn11 commented on orchestrator/session.go
> +						if p.KeyIndex == keyIndex {
actually, scratch that, this information is already in the function scope from the MineNativePhonon call. So we can skip the GetPhononPubKey call and just do this instead: 
```
p.PubKey = hash
```

2022-08-24 19:59 UTC, maevyn11 commented on orchestrator/session.go
>  	go func() {
Think it would be good to turn this anonymous function into a named one, like initMiningAttempt and call that here via go initMiningAttempt instead. Would help separate the logic for generating the id, starting the attempt, and returning it from the actual logic of doing the miningAttempt and tracking the status.

2022-08-24 20:25 UTC, maevyn11 commented
Also, this branch needs to check in the frontend submodule before merging.

2022-08-24 21:01 UTC, zerodouglas commented on gui/api.go
> +	r.HandleFunc("/cards/{sessionID}/phonon/mineNative/status/{miningSessionID}", session.miningReportStatus)
Sure! I like miningAttemptID

2022-08-24 21:05 UTC, zerodouglas commented on gui/api.go
> +		fmt.Println("unable to find mining session")
Noted, I'll also update sessionFromMuxVars following this as well

2022-08-24 21:23 UTC, zerodouglas commented on gui/api.go
> +func sessionFromMiningVars(p map[string]string) (string, error) {
Mux recommends to retrieve them by calling `mux.Vars()`. I could instead of using a helper function, do a 1 liner in the function that needs to retrieve the mining attempt id with `attemptId := vars["miningAttemptID"]`. Regardless if there is no id in the path variable, the server responds with "404 not found" and with no trailing slash, responds with the list of statuses.

2022-08-29 21:19 UTC, npmaile commented on orchestrator/terminal.go
> -type remoteSession struct {
was this unused?

2022-08-29 21:43 UTC, zerodouglas commented on orchestrator/terminal.go
> -type remoteSession struct {
Yes, on the master branch, my linter is showing that this is unused.

2022-09-01 17:19 UTC, maevyn11 commented on gui/api.go
> +func sessionFromMiningVars(p map[string]string) (string, error) {
Cool, thanks for the explanation, was worried that this statement could panic
```
vars := mux.Vars(r)
attemptId := vars["miningAttemptID"]
```

But seems like mux.Vars(r) will always return a miningAttemptID as long as it was included in the URL, so this panic is impossible. Kind of awkward to rely on this implicit guarantee, but I guess as long as we remember that's how mux.Vars works its cleaner than all the redundant error handling.

2022-09-01 17:36 UTC, maevyn11 approved these changes
Change looks really good. Just wondering why all the format updates to the swagger.yml?

2022-09-01 17:36 UTC, maevyn11 commented on gui/swagger.yaml
> +openapi: 3.0.0
What does this change?

2022-09-01 17:36 UTC, maevyn11 commented on orchestrator/session.go
> +	go s.initMiningAttempt(id, difficulty)
Nice, this one looks very tidy now

2022-09-01 17:36 UTC, maevyn11 commented on orchestrator/session.go
> +							p:            p,
Pubkey setting looks good now

2022-09-01 17:36 UTC, maevyn11 commented on orchestrator/session.go
> +
Nice, this whole structure is a nice clean implementation for the needed locking.

2022-09-01 17:46 UTC, zerodouglas commented on gui/swagger.yaml
> +openapi: 3.0.0
There's many properties that were changed with 3.0 than in 2.0. I figured as we're updating documentation, Go version and other resources that it may be best to update the Swagger as well. For instance, produces and consumes was replaced with the new components structure. Hosts, Schemes, and BasePath was replaced with servers.

2022-09-01 17:50 UTC, maevyn11 commented on gui/swagger.yaml
> +openapi: 3.0.0
Gotcha, yea updating seems good then. Doesn't seem like it changes too much but usually pays to stay up to date.

2022-09-02 20:09 UTC, npmaile commented on orchestrator/session.go
> +		case <-cancel:
this can be cleaned up further yet. I'm not going to make you do it now, but consider it if you have nothing going on sometime

2022-09-02 20:11 UTC, npmaile approved these changes
![](https://i.kym-cdn.com/photos/images/original/001/745/592/2bb.gif)

2022-09-06 14:59 UTC, merged