provides better resources for end users
GridPlus/phonon-client pull request #225
Opened 2022-09-02 17:22 UTC by zerodouglas

This PR helps provide a small insight on building the `phonon-client` from source, adds issue templates and other such information that may be helpful.

2022-09-02 18:03 UTC, zerodouglas commented
This should resolve #217 .

2022-09-02 18:11 UTC, zerodouglas commented
It may be better to list the OS field as a text field, allowing the end user to provide the OS's version, name, and other relevant information.

2022-09-02 18:15 UTC, npmaile requested changes

2022-09-02 18:15 UTC, npmaile commented on README.md
> +This repository has a submodule that contains the frontend application. Use the `--recursive` flag to clone all submodules in this repository. Otherwise, you may encounter build errors.
no mention of `make checkout-submodules` target

2022-09-02 18:15 UTC, npmaile commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      options:
also need the version. should be a text box

2022-09-02 18:15 UTC, npmaile commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      options:
should also be a text box.

2022-09-02 18:49 UTC, zerodouglas commented
Removes paragraph in README, due to Nate's change.

2022-09-02 18:50 UTC, zerodouglas commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      options:
Changes can be viewed at https://github.com/GridPlus/phonon-client/pull/225/files#diff-7c49a365610d935ce439e3f241cd3f5d1df89a95d1a674d11ebdb1e518c7335cR18

2022-09-02 18:50 UTC, zerodouglas commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      options:
Change at https://github.com/GridPlus/phonon-client/pull/225/files#diff-7c49a365610d935ce439e3f241cd3f5d1df89a95d1a674d11ebdb1e518c7335cR23

2022-09-02 19:25 UTC, maevyn11 requested changes

2022-09-02 19:25 UTC, maevyn11 commented on CONTRIBUTING.md
> +We may ask questions and so we ask that you respond quickly as possible to your issue.
should be "respond as quickly as"

2022-09-02 19:25 UTC, maevyn11 commented on CONTRIBUTING.md
> +Changes may be requested in your pull request. We ask that you do not use the resolve prompt to resolve your own issues. We will use this prompt once we can verify that the changes are made.
Would include a little more info here about the PR process. Like, merging requires that at least one phonon core developer approve the change, PRs must have no conflicts with master, and CI automated build must pass before changes will be merged.

2022-09-03 04:13 UTC, maevyn11 approved these changes
Leaving approval so this isn't held up while I'm out.

2022-09-09 05:55 UTC, npmaile approved these changes
el gee tee em

2022-09-09 05:59 UTC, merged