adds testnet supported chains to be returned at endpoint
GridPlus/phonon-client pull request #231
Opened 2022-09-12 18:34 UTC by zerodouglas

This PR references the list of chains in the GUI's frontend and provides support to return the specific list of testnet chains from an endpoint called `/listchains`.

2022-09-14 16:51 UTC, npmaile requested changes

2022-09-14 16:51 UTC, npmaile commented on chain/ethChainService.go
> +	chains = append(chains, supportedChains{ChainID: 3, Ticker: "ETH", Name: "Ropsten", CurrencyType: 2})
Do this as at the top of the file at global(to this package) scope instead of building the list each time you run the function

2022-09-14 19:49 UTC, zerodouglas commented on chain/ethChainService.go
> +	chains = append(chains, supportedChains{ChainID: 3, Ticker: "ETH", Name: "Ropsten", CurrencyType: 2})
Changes at https://github.com/GridPlus/phonon-client/blob/60957baabed5c1c955d3238aa2f07da821d5c997/chain/ethChainService.go#L42

2022-09-27 18:25 UTC, npmaile approved these changes

2022-10-12 18:53 UTC, merged