Issue-239
GridPlus/phonon-client pull request #300
Opened 2022-10-09 23:11 UTC by ahinchliff

I've identified why chainId is being misreported for some chains after client restart.

The correct chainId is added to the cache but was not being stored correctly on the card. On client reset the cache is cleared breaking the UI. 

I have supplied a fix but not sure if this is the best solution. Should at least give someone with more knowledge a starting point.

2022-10-10 20:20 UTC, maevyn11 requested changes
Fix makes sense. Just one question about the datatype.

2022-10-10 20:20 UTC, maevyn11 commented on card/phonon.go
> +	chainIDTLV, err := tlv.NewTLV(TagChainID, chainIdBytes)
Nice! So this is the real fix right here right? I can see now that []byte{byte(p.ChainID)}} would not work reliably, maybe it did for values less than one byte or something. 

Is it safe to make ChainID a uint32 though or will we run into problems representing certain chainIDs?

2022-10-10 20:50 UTC, ahinchliff commented on card/phonon.go
> +	chainIDTLV, err := tlv.NewTLV(TagChainID, chainIdBytes)
My thinking was that a max value of 4.2B would be sufficient to cover future chain ids but maybe that is too much of an assumption. Let me know if you want me to change this back.

2022-10-12 00:45 UTC, maevyn11 commented on card/phonon.go
> +	chainIDTLV, err := tlv.NewTLV(TagChainID, chainIdBytes)
ah no, I think I got my byte math way wrong at first look. I think 4.2B max value is more than sufficient.

2022-10-12 00:48 UTC, maevyn11 approved these changes
Good catch and thanks for the fix! Seems the caching layer hid this issue from view in the test phase. Fix looks good to me. 

@zerodouglas any chance this issue played a part in the chainID issues when sending to cards. It looks like to me that with the current implementation any chainID > 1 byte in length would've been mangled on input and output to the card.

2022-10-12 02:48 UTC, ahinchliff commented
No worries. Just a reminder I dont have merge permissions so someone else will need to do the honours.

2022-10-12 18:53 UTC, merged