Asset validation
GridPlus/phonon-client pull request #347
Opened 2022-12-29 15:41 UTC by zerodouglas

This pull request references #319 and the initial design specification outlined in phonon-network/asset-validation with the following proposed implementation:

```go
valid, err := s.validator.Validate(proposedPhonons)
if err != nil {
  return err
}
```
 
When providing the validator the collection of proposed phonons to validate, each phonon is evaluated based on its currency type. For example, this implementation only supports phonons that are ETH currency (type: 2). This allows any contributor to create a validator for such currency by using the interface defined by "AssetValidator".

2022-12-29 16:16 UTC, maevyn11 requested changes
Couple small things that need changing, otherwise all the improvements look good.

2022-12-29 16:16 UTC, maevyn11 commented on chain/ethChainService.go
> +				Err:   errors.New("phonon balance is less than what is stated in denomination value"),
should assign this to an error constant.

2022-12-29 16:16 UTC, maevyn11 commented on validator/validator.go
> +			result, err := v.ethValidator.Validate(p)
Does this loop work? I think initializing result inside the for loop here will erase the contents of result from the last iteration. Not what we want. Think this is a good case to use named return parameters. 

```suggestion
//In the method sig
func (v *Validator) Validate(proposal []*model.Phonon) (results []*AssetValidationResult, err error) {
...
case 2: 
result, err := v.ethValidator.Validate(p)
...
results = append(results, result)
```

2022-12-29 16:16 UTC, maevyn11 commented on validator/validator.go
> +	assetValidator AssetValidator
why is the interface a member of this struct?

2023-01-09 23:13 UTC, maevyn11 requested changes
Needs to use the sim as the backend by injecting the dependency into EthChainService instead of using Ganache

2023-01-10 00:02 UTC, zerodouglas commented on chain/ethChainService.go
> +var ErrUntrustworthy = errors.New("phonon balance is less than what is stated in denomination value")
Agree, I like ErrBalanceTooLow

2023-01-12 20:30 UTC, maevyn11 requested changes
Mostly looks good but there are a couple concerning elements I commented on.

2023-01-12 20:30 UTC, maevyn11 commented on chain/ethChainService_test.go
> +	lowValue, err := model.NewDenomination(big.NewInt(1000000000000000))
maybe add some comments on how many zeroes there are here? It's really hard to tell at a glance whether this value is different than the one on 125

2023-01-12 20:30 UTC, maevyn11 commented on chain/ethChainService_test.go
> +	}
instead of changing values by index, I suggest it would be a lot easier to read this if you created a bunch of phonons up front with just the different keyIndexes, and then modified the fields directly one at a time before calling validate. As it is, you have to scan up and down from here to the test case check to see what's being done.

2023-01-12 20:30 UTC, maevyn11 commented on chain/ethChainService_test.go
> +	valid, err := ethChainSrv.Validate(phonons)
valid should be called validationResult, valid makes it seem like it's a boolean.

2023-01-12 20:30 UTC, maevyn11 commented on chain/ethChainService_test.go
> +			assert.EqualError(t, r.Err, model.ErrUnsupportedCurrency.Error())
Would prefer this stuff be checked using regular golang equality statements instead of introducing a new assert dependency, but I know that's more of a style preference, so I'll leave it up to you. 

Suggest like: 
```
if !(r.Valid == false && r.Err == model.ErrUnsupportedCurrency) {
  t.Error("err message")
}
```

2023-01-12 20:30 UTC, maevyn11 commented on model/assetValidator.go
> +var ErrInvalidEthAddress = errors.New("invalid ethereum address")
this looks nice

2023-01-12 20:30 UTC, maevyn11 commented on orchestrator/session.go
> +	// }
Dead code or does this still have to be integrated into session?

2023-01-12 20:43 UTC, zerodouglas commented on chain/ethChainService_test.go
> +		return simEVM, nil, nil, nil
Agreed, it's initialized within the function so it will always be nil. I'll remove it :)

2023-01-12 20:46 UTC, zerodouglas commented on chain/ethChainService_test.go
> +			assert.EqualError(t, r.Err, model.ErrUnsupportedCurrency.Error())
I like your suggestion. It removes the dependency of assert and makes it more clear in the end.

2023-01-12 20:48 UTC, zerodouglas commented on orchestrator/session.go
> +	// }
I can certainly remove it, I commented it out at that time when I removed the package that this function depended on, but simply forgot about it.

2023-01-12 21:27 UTC, zerodouglas commented on chain/ethChainService_test.go
> +	pubKey, err := generatePubKey()
Understandable, I had migrated this out since I figured "FundEthPhonon" was not the right name for both creating a phonon and adding funds to it. But now that you've pointed it out, I agree, it's pointless and adds clutter, since the fund function takes the pointer that can just be referenced in the test case.

2023-01-12 21:30 UTC, zerodouglas commented on chain/ethChainService_test.go
> +	}
So, by that I suppose you mean just create a bunch of local variables with different values and then value them at a time. Can Do :)

2023-01-12 22:22 UTC, maevyn11 commented on chain/ethChainService_test.go
> +	}
something like that yea

2023-01-12 22:24 UTC, maevyn11 commented on orchestrator/session.go
> +	// }
yea let's remove it, better not to leave clutter in the codebase

2023-01-18 17:12 UTC, maevyn11 requested changes

2023-01-18 17:12 UTC, maevyn11 commented on chain/ethChainService_test.go
> +	pubKey, err := generatePubKey()
pubkey needs to loop so that all funds aren't sent to the same address

2023-01-24 14:58 UTC, zerodouglas commented on chain/ethChainService_test.go
> +	pubKey, err := generatePubKey()
Fixed in https://github.com/GridPlus/phonon-client/blob/97e6af9466611211b27c5f3e874aeb2f36860fd8/chain/ethChainService_test.go#L177

2023-01-24 15:09 UTC, zerodouglas commented on chain/ethChainService.go
> +		}, nil
Resolution starts https://github.com/GridPlus/phonon-client/blob/97e6af9466611211b27c5f3e874aeb2f36860fd8/chain/ethChainService.go#L49

2023-01-27 19:15 UTC, maevyn11 commented on chain/ethChainService.go
> +			Valid: true,
why is Valid true here? Shouldn't it be false?

2023-01-27 19:16 UTC, maevyn11 commented on chain/ethChainService_test.go
> +	// 1e zeros
typo?

2023-01-27 19:19 UTC, maevyn11 commented on chain/ethChainService_test.go
> +			err:   model.ErrBalanceTooHigh,
nice, this looks much better

2023-01-27 19:20 UTC, maevyn11 commented on chain/ethChainService.go
> +			Valid: true,
probably doesn't matter since we're going to check the error. But if in future we don't this could give goofy results.

2023-01-27 19:20 UTC, maevyn11 approved these changes
Looks good, a couple small nits.

2023-02-15 16:24 UTC, merged