Jumpbox fix
GridPlus/phonon-client pull request #74
Opened 2022-01-18 08:40 UTC by npmaile

Long awaited Jumpbox fix. Sending phonons back and forth over remote works and has been tested > 10 times in a row.

2022-01-20 22:40 UTC, maevyn11 requested changes

2022-01-21 18:04 UTC, npmaile commented on orchestrator/terminal.go
this will be done at the same time as the separation of the connect and pairing steps.

2022-01-21 18:06 UTC, npmaile commented on remote/client.go
> +		{
I just didn't want to put it in it's own function. I can move it out if you want

2022-01-21 18:06 UTC, npmaile commented on remote/client.go
> +		{
otherwise it would have to be a single statement

2022-01-21 20:48 UTC, maevyn11 commented on orchestrator/terminal.go
makes sense

2022-01-21 20:52 UTC, maevyn11 commented on remote/client.go
> +		{
I'm fine with the if and the statement being here, you just don't need the outer brackets. 2 statements works fine as in line 155 above.

2022-01-26 15:36 UTC, npmaile commented on gui/api.go
>  	sessionName, ok := p["sessionID"]
It's a helper function to grab an APISession object given an input of the parsed mux vars. the sessionID is the name of that variable and it has to be parsed like this.

2022-01-26 15:36 UTC, npmaile commented on gui/api.go
yes

2022-01-26 16:03 UTC, npmaile commented on remote/client.go
>  }
I think mine more accurately reflects the spiritual influence behind a do-while, so I'm going to sadly send your code to the depths.

2022-01-27 21:10 UTC, maevyn11 commented on gui/api.go
>  	sessionName, ok := p["sessionID"]
OK got it.

2022-01-28 16:20 UTC, maevyn11 commented on remote/client.go
> +		}
Not sure why you resolved this one?

2022-01-28 16:22 UTC, maevyn11 commented on remote/client.go
> +	log.Info("client has crt: ", s.Cert)
?

2022-01-28 16:27 UTC, maevyn11 commented on gui/api.go
> +type apiSession struct {
comments on this?

2022-01-28 18:51 UTC, maevyn11 commented on gui/api.go
> +type apiSession struct {
Right, I see. Using this as a wrapper to define methods makes sense. WebRequestHandler?

2022-01-28 18:54 UTC, maevyn11 commented on remote/client.go
> +		}
Helper is good. We'll have to changes these IDs for something more robust in future to avoid collissions anyway.

2022-01-28 18:55 UTC, maevyn11 approved these changes
Looks good. Left one comment suggesting changing apiSession to WebRequestHandler but we can consider that for the next PR.

2022-01-28 19:30 UTC, merged