Separate connect pair
GridPlus/phonon-client pull request #87
Opened 2022-01-27 20:27 UTC by npmaile

feel free to look at the code. 
it's not quite ready to go in yet.

2022-02-09 22:46 UTC, maevyn11 requested changes

2022-02-09 22:46 UTC, maevyn11 commented on remote/server.go
>  		//TODO: use a real error, possibly from cert package
Still TODO or we happy with this error message now?

2022-02-09 22:46 UTC, maevyn11 commented on model/counterpartyCard.go
> +
Think this message type should stay encapsulated in the remote package. Since we eventually want to implement multiple networking types and enable external apps to develop them I think we should keep the core client to card stuff as isolated as possible from the Jumpbox implementation.

2022-02-09 22:46 UTC, maevyn11 commented on repl/cardPairing.go
>  	if err != nil {
I don't love this pattern of manually setting RemoteCard on activeCard. It's not clear to the caller that this is how you establish a remote connection with another card and it seems likely to lead to accidental panics when a RemoteCard is not properly initialized. 

Feels like this is ripe for an interface that unifies LocalCounterParty and JumpboxCounterparty and provides a method or two on session to connect to either one. Thoughts?

2022-02-09 22:46 UTC, maevyn11 commented on repl/cardPairing.go
> +		c.Err(err)
Needs a return afterwards so that the "successfully paired" message doesn't print when there's an error. Also does c.Err print the message?

2022-02-09 22:46 UTC, maevyn11 commented on session/remoteClient.go
guessing this package moved for similar reasons as the others? Not sure it belongs in session.

2022-03-09 15:46 UTC, npmaile commented
Opened a new pr because changes were going to be too divergent.

2022-03-09 15:46 UTC, closed without merging