Phonon deposit
GridPlus/phonon-client pull request #89
Opened 2022-01-28 19:45 UTC by maevyn11

2022-01-28 20:00 UTC, npmaile requested changes

2022-01-28 20:00 UTC, npmaile commented on gui/api.go
> +	reqBody, err := ioutil.ReadAll(r.Body)
You can kill a couple of lines here by making a json decoder off of the body directly and use that. 

err := json.NewDecoder(r.Body).Decode(&denoms)
    if err != nil {
        http.Error(w, err.Error(), http.StatusBadRequest)
        return
    }

2022-01-28 20:00 UTC, npmaile commented on chain/chain.go
> +func DeriveAddress(p *model.Phonon) (address string, err error) {
I'd rather the DeriveAddress be an interface type, and you just call it on an ethereum provider or a bitcoin provider or whichever one. 

That way it's a little easier to test the calling functions because you can put in a test struct type that just has a dummy implementation instead of having a separate case for it.

2022-02-03 23:03 UTC, maevyn11 commented on gui/api.go
> +	reqBody, err := ioutil.ReadAll(r.Body)
Neat I like that.

2022-02-03 23:09 UTC, maevyn11 commented on chain/chain.go
> +func DeriveAddress(p *model.Phonon) (address string, err error) {
yea, this could use some work. You could make it an interface type but then you'd still need to have the switch on currencyType that refers to the interface somewhere.  

I think it should maybe be a method on CurrencyType? That would be an easy place to collect chain specific stuff so there's a clean interface for external contributions. 

I guess I'm talking myself into an interface and just having a central method that switches which implementation is used based on the currencyType. Will change this.

2022-02-04 22:57 UTC, maevyn11 commented on gui/api.go
> +	reqBody, err := ioutil.ReadAll(r.Body)
Suggestion implemented.

2022-02-04 22:58 UTC, maevyn11 commented on chain/chain.go
> +func DeriveAddress(p *model.Phonon) (address string, err error) {
There's a wonky version of the interface in there now. Still need to figure out where to initialize it and exactly how the rest of the phonon data structure utilizes it.

2022-02-07 15:10 UTC, npmaile approved these changes

2022-02-14 17:26 UTC, merged