Basic caching
GridPlus/phonon-client pull request #93
Opened 2022-02-16 01:06 UTC by npmaile

this should implement a basic caching scheme to make card operations quite a bit faster.

2022-02-24 20:36 UTC, maevyn11 requested changes
Looks good for the most part. Just a couple small comments that I think will make it more robust.

2022-02-24 20:36 UTC, maevyn11 commented on gui/api.go
> +		phonons = []*model.Phonon{}
Where does cachePopulated get set? I don't see it in createPhonon, initDeposit, or finalizeDeposit.

2022-02-24 20:36 UTC, maevyn11 commented on gui/api.go
> +	}
OK, I see. So this just caches lists after the first one.

2022-02-24 20:36 UTC, maevyn11 commented on gui/api.go
>  	err = sess.SetDescriptor(p)
seems like this should maybe be after the error is checked on `err = sess.SetDescriptor`. If that fails then the cache and card will be out of sync for this keyIndex.

2022-02-24 20:36 UTC, maevyn11 commented on gui/api.go
> +
again this should probably be after the error check. If the key fails to send the cache will be out of sync.

2022-02-24 20:40 UTC, npmaile commented on gui/api.go
> +	}
yeah, the idea is that the cache isn't fully populated until a full list has been done at least one time. After that anything that would modify the cache is modified in the cache along with the on card change happening

2022-02-24 21:38 UTC, npmaile commented on gui/api.go
>  	err = sess.SetDescriptor(p)
fixed

2022-02-24 21:38 UTC, npmaile commented on gui/api.go
> +
fixed

2022-02-25 00:51 UTC, maevyn11 approved these changes
LOOKS GOOD

2022-02-25 00:51 UTC, merged