wip
GridPlus/phonon-client pull request #97
Opened 2022-03-09 15:43 UTC by npmaile

Nearly complete. Needs testing and a completion of the localcounterparty

2022-03-09 20:39 UTC, maevyn11 requested changes
Overall I think the PR looks good. Mostly fiddly formatting comments and clarifying questions from me. Of course also waiting for local counterparty to be implemented before final approval.

2022-03-09 20:39 UTC, maevyn11 commented on model/sessionRequest.go
> +
OK, so this is like an interface definition of the actions that a counterparty can request of a session it has connected to? 

And the requests are identified by a string returned by GetName() which matches the struct name, where the handleRequest method in session uses a switch statement to determine how each request is handled? 

Just posing questions to make sure I understand the design.

2022-03-09 20:39 UTC, maevyn11 commented on orchestrator/session.go
> +	if err != nil {
Ok, so this s.remoteMessageChan arg is how the remote connection communicates with the local session. Took me a minute to find how the handleRequest loop was being contacted. 

Will this work correctly if a user tries to connect to multiple cards within a single session? For example, pairing with card A, doing a transaction, and then pairing with card B to do a transaction. I suspect the s.remoteMessageChan should only receive messages from one card at a time so as long as that's the case it should be alright? Wondering if the downstream steps like ConnectToCounterparty and Jumpbox have been tested in this case? Not critical at this stage but something to consider moving forwards.

2022-03-09 20:39 UTC, maevyn11 commented on orchestrator/terminal.go
> +var ErrNoSession error = errors.New("No connected session with id found")
caps in error message

2022-03-09 20:39 UTC, maevyn11 commented on orchestrator/session.go
> +	go s.handleIncommingSessionRequests()
I was skeptical at first but after reading through most of the code I think having a request handler loop in session actually makes a lot of sense. My concern is mainly that I worry about coupling Session with the implementation details of Jumpbox, therefore making it hard to implement other network providers like local and decentralized p2p, but I think the design here sufficiently separates the details so that concerns can be fairly easily separated when we need to.   

Also, typo here, too many mm's in incoming.

2022-03-09 20:39 UTC, maevyn11 commented on orchestrator/session.go
> +		case <-s.remoteMessageKillChan:
What's the idea with the remoteMessageKillChan? I don't see it being used anywhere atm.

2022-03-09 20:39 UTC, maevyn11 commented on remote/v1/message.go
v1 here presumably so Session could easily swap out the v1 client for an entirely different v2 implementation in future? Is the idea here that we might want to enable both clients to be an option so this is better than just versioning the code?

2022-03-09 20:39 UTC, maevyn11 commented on orchestrator/session.go
> +package orchestrator
Soooo...I'll bite. Why did session move to orchestrator? I suppose I don't see a problem with it, just curious.

2022-03-09 20:39 UTC, maevyn11 commented on remote/v1/client/client.go
> +// Requests into the card session
Do these calls make requests of the local session or of the remote session?

2022-03-09 20:39 UTC, maevyn11 commented on orchestrator/session.go
> +func (s *Session) handleRequest(r model.SessionRequest) {
I don't have a good solution for it but it feels like this logic is being redefined several times throughout the program. Here, in remote client, and in remote server. It feels like we should be able to abstract that away somehow, though we're probably too far down this path to do it now. Just food for thought.

2022-03-09 20:59 UTC, npmaile commented on orchestrator/session.go
>  }
i wrote that line shortly after a Eureka! moment on how the app should be structured in the future given that it will run on things with secure enclaves other than the smart card.

2022-03-09 21:01 UTC, npmaile commented on orchestrator/session.go
> +		case <-s.remoteMessageKillChan:
i just felt weird writing an infinite loop with no way of killing it. the channel will be used when we come up with a mechanism for deleting sessions

2022-03-14 15:45 UTC, maevyn11 requested changes
Few small comments. Still needs a local counterparty implementation.

2022-03-14 15:45 UTC, maevyn11 commented on orchestrator/session.go
> +		identityPubKey:        &ecdsa.PublicKey{},
Shouldn't this zero as nil instead of &ecdsa.PublicKey? Wondering if this is another editor autofill issue.

2022-03-14 15:45 UTC, maevyn11 commented on orchestrator/session.go
>  }
OK, I get the secure element reference now. Still find the name awkward though, I think because Usage is redundant with the fact that it's a lock. What about SecElementMtx?

2022-03-14 15:45 UTC, maevyn11 commented on remote/v1/client/client.go
>  	c.sessionRequestChan <- req
logs should avoid capitalization too.

2022-03-15 15:51 UTC, npmaile commented on cmd/JumpBox.go
>  	"github.com/spf13/cobra"
for easy replacement if we need to do so. Also, there will likely be other remote clients for other communication mediums other than go -> go http/2

2022-03-15 15:52 UTC, npmaile commented on orchestrator/session.go
> +package orchestrator
the phonon terminal being in a different package than the terminal didn't work great for facilitating communication between sessions with the separate pair/connect steps

2022-03-15 15:52 UTC, npmaile commented on remote/v1/client/client.go
> +// Requests into the card session
into the local session. That way we have clear frontend -> terminal -> session -> remote ownership heirarchy instead of having the remote and session be peers. The remote can politely ask for requests of the session it's connected to instead of having control.

2022-03-15 15:52 UTC, npmaile commented on orchestrator/session.go
> +func (s *Session) handleRequest(r model.SessionRequest) {
It's deceptively similar, but ultimately different

2022-03-15 15:52 UTC, npmaile commented on remote/v1/client/client.go
>  	c.sessionRequestChan <- req
will fix across the entire repo in a later pr. There's mistakes in other files and I don't want the pr to include them. it's a fairly simple regex to do it, so it'll take approx 2 minutes to do.

2022-03-22 17:09 UTC, maevyn11 requested changes
Having some issues with the localCounterParty functionality. Haven't been able to get the tests, REPL, or cmd pairCardToCard command to work on my machine with two alpha cards. There are also a few minor outstanding comments to address. Once these are resolved we should be good to merge this in with the current master.

2022-03-22 17:09 UTC, maevyn11 commented on orchestrator/session_test.go
> +func TestE2ELocalSendPhonon(t *testing.T) {
Seems like there are some issues running this test for local counterparty. Also get an error trying to run cmd/pairCardToCard with two fresh cards installed with alpha applets.  `go run main/phonon.go pairCardToCard -r 0 -s 1`

2022-03-22 17:09 UTC, maevyn11 commented on repl/cardPairing.go
> +	err = activeCard.ConnectToCounterparty(otherCards[selection].GetName())
getting an error trying to pair two alpha cards in the repl. 
```
starting pairing with  04ee191cc71fd218
{"level":"info","msg":"returning error from ConnectRemoteSession","time":"2022-03-22T12:04:14-05:00"}
Error occured in pairing process: counterparty card not found
```

2022-03-22 17:09 UTC, maevyn11 commented on orchestrator/session.go
> +		case <-s.remoteMessageKillChan:
ok, works as a placeholder for now then.

2022-03-22 21:09 UTC, npmaile commented on orchestrator/session_test.go
> +func TestE2ELocalSendPhonon(t *testing.T) {
test is functioning now.

2022-03-23 06:17 UTC, npmaile commented on repl/cardPairing.go
> +	err = activeCard.ConnectToCounterparty(otherCards[selection].GetName())
fixed.

2022-03-23 06:17 UTC, npmaile commented on orchestrator/session_test.go
> +func TestE2ELocalSendPhonon(t *testing.T) {
fixed pairCardToCard command.

2022-03-23 06:18 UTC, npmaile commented on orchestrator/session.go
> +		identityPubKey:        &ecdsa.PublicKey{},
done.

2022-03-24 17:05 UTC, maevyn11 commented on repl/cardPairing.go
> +	err = activeCard.ConnectToCounterparty(otherCards[selection].GetName())
nice, works great now. Only thing left to change is setting PairCounterparty to pairCounterparty and showing what the argument is supposed to be in the repl help text

2022-03-24 17:12 UTC, maevyn11 approved these changes
Looks good!

2022-03-24 17:27 UTC, merged